### PR TITLE
Remove 1000 limit on API calls

### PR DESCRIPTION
**Pull request by imsickofmaps**

### CODE REVIEW

**Comment by imsickofmaps** [comment]
@smn please review. Required for integration with 3rd party downloader. Currently maxing at 1000.

**Comment by smn** [comment]
Where is that stuff persisted? Got a link to the docs for me?

**Comment by imsickofmaps** [comment]
http://django-tastypie.readthedocs.org/en/latest/settings.html and https://github.com/toastdriven/django-tastypie/blob/master/tastypie/resources.py#L71-L72

**Comment by smn** [comment]
Will this continue to work even if the db has a million entries? Django buffers the output of all HTTP responses, chances are this'll result in timeouts. Why can't the client implement pagination?

**Comment by smn** [comment]
:+1: much better.

**Pull request merged**
