### PR TITLE
create ability for district admin to register on the system via USSD

### PR DESCRIPTION
**Pull request by gitumarkk**
The purpose of this is to create the district admin user django models and api endpoint that will receive data posted from vumi go.

Includes #85 (which was meant to allow rts staff who don't have the district admin to be able to send an sms).
### User story

so that I can create learner performance data as a district admin I can register on the system
### Details

In order to for the district admin to register.

> Need to create a DistrictAdminProfile model.
>     - date_of_birth
>     - id_number
>     -  first_name
>     - last_name
>     - created_at
>     - district
> Expose the DistrictAdminProfile model to API endpoint

### CODE REVIEW

**Comment by gitumarkk** [comment]
Make sure to review #90 before this as it fixes a critical bug and is merged in this.

**Comment by gitumarkk** [comment]
@imsickofmaps ready for review.

**Comment by smn** [comment]
Do you guys have any idea why this project takes 30m to build on Travis? It's somewhat blocking all other builds for praekelt.

**Comment by imsickofmaps** [comment]
@smn  No idea. It's a three minute build locally...

**Comment by imsickofmaps** [comment]
@smn ready for review - after #90

**Comment by imsickofmaps** [comment]
@smn landing - I have more changes to this project to make this afternoon that I'm going to be spending too much time do merge conflict and repo management than coding and not enough time delivering value. We can discuss fallout later.

**Pull request merged**
