### PR TITLE
Eliminate HeadTeacher and DistrictAdmin Requirements

### PR DESCRIPTION
**Pull request by gsvr**
https://praekelt.atlassian.net/browse/RZ-26

### CODE REVIEW

**Comment by gsvr** [comment]
@imsickofmaps Ready for review.

**Comment by imsickofmaps** [comment]
Missing migration?

**Comment by gsvr** [comment]
I thought I needed a migration, too, but when I ran the schemamigration --auto, it reported "Nothing seems to have changed".  It actually makes sense, though, since null=True is the database blank value, whilst the blank=True that we just added is just django field validation.  At least as far as I understand it.

**Comment by imsickofmaps** [comment]
fp

Of course... thanks :+1:

**Pull request merged**
