### PR TITLE
two duplicate records written for teacher performance

### PR DESCRIPTION
**Pull request by imsickofmaps**
maybe parseInt these values before compare: https://github.com/praekelt/go-rts-zambia/blob/develop/js_sandbox/lib/go-rts-zambia.js#L366

### CODE REVIEW

**Comment by imsickofmaps** [comment]
Tiny so self reviewed...

**Comment by laurenkotze** [comment]
Hey, can we please re-open this issue? On the production server (zambiaschoolgateway.com), there are still multiple duplicates. And I'm pretty sure these people aren't registering twice, because I registered only once and it shows up twice. Screenshot attached. Tks

**Comment by smn** [comment]
Removing the screenshot because it contained msisdns and this repository is public.

**Comment by smn** [comment]
This issue still will need to be re-opened though. Blurred the screenshot and re-published [here](https://www.evernote.com/shard/s313/sh/c3f6cbcc-3c9b-4645-b837-979c3f79c87d/b452cae285631bcd9da1a6fa6dc2c2c7)

**Comment by laurenkotze** [comment]
oops sorry, thanks Simon!

**Pull request merged**
