### PR TITLE
Admin can send broadcast message to active MSISDNs

### PR DESCRIPTION
**Pull request by gitumarkk**
This is now a non-Vumi issue. Feature needs adding to Django CMS and calling Vumi Go API to be created: https://github.com/praekelt/vumi-go/issues/657

### CODE REVIEW

**Comment by gitumarkk** [comment]
I am getting an unusual bug, when I run the unittests using `.\manage.py test -s` the sms app fails but on running the individual app tests i.e. `.\manage.py test sms -s` the specific app tests pass, not sure why? I have created the following gists giving the traceback https://gist.github.com/gitumarkk/7d6e915f8773b90b2b23

**Comment by imsickofmaps** [comment]
@smn Travis is failing because of: https://gist.github.com/imsickofmaps/d575070f4f62624adf39 ... have you seen this before? Tests pass in isolation but not in wider scope?

**Comment by smn** [comment]
Are tests cleaning up properly after themselves?

On 26 September 2013 00:14, Mike Jones notifications@github.com wrote:

> @smn https://github.com/smn Travis is failing because of:
> https://gist.github.com/imsickofmaps/d575070f4f62624adf39 ... have you
> seen this before? Tests pass in isolation but not in wider scope?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/praekelt/go-rts-zambia/pull/12#issuecomment-25129333
> .

## 

Simon de Haan | Chief Engineer Praekelt Foundation

praekeltfoundation.org | praekelt.com
M: +27 (0) 76 449 3806  |  http://twitter.com/smn

**Comment by gitumarkk** [comment]
@smn I am not sure, just using the standard django testing procedure, should I be writing teardown functions after each test?

**Comment by imsickofmaps** [comment]
@gitumarkk I've found the root cause of this failure. When running in the wider context the role filtering is applied and the Send SMS is disabled until the user has a district applied to them for zone filtering. I've removed these tests for now until a solution can be found. (cc @smn)

**Comment by imsickofmaps** [comment]
Travis is failing on Python 2.6 set creation... 2.7 in production so ignoring.

**Comment by imsickofmaps** [comment]
:+1:

**Comment by smn** [comment]
tsk tsk tsk. Please fix py26 or tell Travis not to build against 2.6. Until you do Travis will be useless to you.

**Pull request merged**
