### PR TITLE
Add drop-down options for teacher years experience in Gateway

### PR DESCRIPTION
**Pull request by gsvr**
https://praekelt.atlassian.net/browse/RZ-25?jql=project%20%3D%20RZ%20AND%20resolution%20%3D%20Unresolved%20AND%20priority%20%3D%20Critical%20ORDER%20BY%20key%20DESC

### CODE REVIEW

**Comment by gsvr** [comment]
Incorporates #105:
https://praekelt.atlassian.net/browse/RZ-23?jql=project%20%3D%20RZ%20AND%20resolution%20%3D%20Unresolved%20AND%20priority%20%3D%20Critical%20ORDER%20BY%20key%20DESC

**Comment by gsvr** [comment]
@imsickofmaps Ready for review.  There were 2 things I wasn't sure of:
1. Should I have added tests?  It seems unlikely.
2. I just edited the /add page forms rather than setting choices in the actual models.  I thought this is what you meant but let me know if I misinterpreted.

**Comment by imsickofmaps** [comment]
Sorry I did mean setting choices in the actual models like: https://docs.djangoproject.com/en/dev/ref/models/fields/#choices

**Comment by gsvr** [comment]
@imsickofmaps Ready for re-review.

**Comment by imsickofmaps** [comment]
:+1:

**Comment by imsickofmaps** [comment]
:+1:

**Pull request merged**
