### PR TITLE
move to new JSON api helper

### PR DESCRIPTION
**Pull request by imsickofmaps**

### CODE REVIEW

**Comment by smn** [comment]
:+1: but please get Travis in shape? https://travis-ci.org/praekelt/go-rts-zambia/jobs/12616164 It's still complaining about py2.6 incompatible sets.

**Comment by imsickofmaps** [comment]
@smn this is tiny so I'm merging

**Comment by imsickofmaps** [comment]
@smn oh bugger, Github didn't show me the comment above - will sort Travis

**Comment by imsickofmaps** [comment]
@smn Travis is HAPPY \o/

**Pull request merged**
